- apps/raddix/next.config.js
- apps/raddix/package.json
- packages/vintex/package.json
- packages/vintex/src/button/button.tsx
- packages/vintex/src/button/index.ts
- packages/vintex/src/index.ts
- packages/vintex/tsconfig.json
- pnpm-lock.yaml
Create an inner package where all components will be managed
> feat: add Vintex UI

- apps/raddix/src/hooks/isMobile.ts
turn logic into a single function
> refactor: replace deprecated addListener in useIsMobile

- apps/raddix/package.json
- apps/raddix/postcss.config.js
- apps/raddix/src/pages/_app.tsx
- apps/raddix/tailwind.config.js
- packages/tailwind-config/package.json
- packages/tailwind-config/postcss.config.js
- packages/tailwind-config/tailwind.config.js
- packages/vintex/package.json
- packages/vintex/postcss.config.js
- packages/vintex/src/globals.css
- packages/vintex/tailwind.config.js
- pnpm-lock.yaml
add tailwind base configuration
> chore: tailwindcss setup

- apps/raddix/src/components/header/header.comp.tsx
- apps/raddix/src/hooks/useIsMobile.ts
- apps/raddix/src/layouts/docs/docs.layout.tsx
update the useIsMobile hook code according to linter rules
> fix(raddix): update code according to linter rules

- README.md
add docs of development in README.md
> feat: add docs of development

- packages/tailwind-config/tailwind.config.js
Is the spacing config ok this way?
> feat: add theme to tailwind-config

- .husky/pre-commit
- .lintstagedrc
- package.json
- pnpm-lock.yaml
Configure Git Hooks via Husky and run linters before committing your code.
> chore: add husky and lint-staged

- packages/tsconfig/reactjs.json
- packages/vintex/src/index.ts
- packages/vintex/src/pagenav/index.ts
- packages/vintex/src/pagenav/pagenav.tsx
I changed a bit the algorithm to detect the hierarchy of elements. 
If an H3 comes after an H2, the H3 will be a child of H2. The same if after the H3 comes an H4. It seems to me that it is more comfortable for recursion in the Tree component.
> feat(vintex): add pagenav component

- packages/colors/package.json
- packages/tailwind-config/package.json
- packages/tailwind-config/tailwind.config.js
- pnpm-lock.yaml
Change the color palette of tailwind with that of vintach
> feat: add color system of vintach

- packages/vintex/src/footer/footer.tsx
- packages/vintex/src/footer/index.ts
- packages/vintex/src/index.ts
> feat(vintex): add footer component

- packages/vintex/package.json
- packages/vintex/src/index.ts
- packages/vintex/src/sidebar/index.ts
- packages/vintex/src/sidebar/sidebar.tsx
- packages/vintex/src/sidebar/sidebar.types.ts
- pnpm-lock.yaml
> feat(vintex): add sidebar component

- apps/raddix/src/layouts/app/app.layout.tsx
Addd Footer component from packages/vintex and old files removed
> refactor: replace footer component

- packages/vintex/src/index.ts
- packages/vintex/src/pagination/index.ts
- packages/vintex/src/pagination/pagination.tsx
> feat: add pagination component

- apps/raddix/package.json
- packages/vintex/package.json
- packages/vintex/src/pagenav/pagenav.tsx
- pnpm-lock.yaml
When the header is visible activate the matching navigation element
> feat: active header element.

- apps/raddix/data/docs/utilities/use-scroll-spy/use-scroll-spy.en.mdx
- apps/raddix/data/docs/utilities/use-scroll-spy/use-scroll-spy.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
Add documentation of the useScrollSpy hook
> docs: add useScrollSpy documentatión

- apps/raddix/data/docs/utilities/use-scroll-spy/use-scroll-spy.en.mdx
- apps/raddix/data/docs/utilities/use-scroll-spy/use-scroll-spy.es.mdx
Add more context to useScrollSpy hook documentation
> refactor: copy in use-scroll-spy.mdx files

- apps/raddix/src/components/mdx.tsx
Minor tweaks to mdx component styles
> refactor: MDX component styles

- apps/raddix/data/docs/interactions/use-click-outside/use-click-outside.en.mdx
- apps/raddix/data/docs/interactions/use-click-outside/use-click-outside.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
- apps/raddix/examples/use-click-outside/example1.tsx
- apps/raddix/package.json
- pnpm-lock.yaml
Add documentation of useClickOutside hook
> docs(raddix): useClickOutside hook

- apps/raddix/data/docs/utilities/use-toggle/use-toggle.en.mdx
- apps/raddix/data/docs/utilities/use-toggle/use-toggle.es.mdx
- apps/raddix/examples/use-toggle/example1.tsx
Add documentation of useToggle hook
> docs(raddix): useToggle hook

- apps/raddix/data/docs/interactions/use-keyboard/use-keyboard.en.mdx
- apps/raddix/data/docs/interactions/use-keyboard/use-keyboard.es.mdx
- apps/raddix/examples/use-keyboard/example3.tsx
- apps/raddix/package.json
- pnpm-lock.yaml
Add documentation and example of the `globalEvent` option of the `useKeyboard` hook
> docs(raddix): add `globalEvent` option

- apps/raddix/data/docs/utilities/use-count-down/use-count-down.en.mdx
- apps/raddix/data/docs/utilities/use-count-down/use-count-down.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
- apps/raddix/examples/use-count-down/example1.tsx
- apps/raddix/examples/use-count-down/example2.tsx
- apps/raddix/package.json
- pnpm-lock.yaml
Wrote down the documentation for the new hook useCountDown 💯
> docs: full docs for use-count-down hook

- apps/raddix/package.json
- apps/raddix/src/components/code-block/code-block.tsx
- apps/raddix/src/components/code-block/theme.ts
- apps/raddix/src/components/mdx.tsx
- apps/raddix/src/pages/_app.tsx
- apps/raddix/src/pages/_document.tsx
- apps/raddix/src/styles/main.css
- pnpm-lock.yaml
fixed flickering font in CodeBlock component and added corresponding colors to code highlighting.
> fix(raddix): flickering font in CodeBlock component

- apps/raddix/next.config.js
- apps/raddix/package.json
- apps/raddix/src/components/mdx.tsx
- apps/raddix/src/components/menu.tsx
- apps/raddix/src/layouts/docs.tsx
- apps/raddix/src/lib/mdx.ts
- apps/raddix/src/pages/_app.tsx
- apps/raddix/src/utils/constants.ts
- packages/vintex/package.json
- packages/vintex/src/pagenav/pagenav.tsx
- packages/vintex/src/sidebar/sidebar.tsx
- pnpm-lock.yaml
- settings/tailwind/tailwind.config.js
- Max width increased to 1360px
- The font size of the titles and subtitles was decreased
- Reduced sidebar padding
> feat: improve documentation design

- apps/raddix/data/docs/utilities/use-counter/use-counter.en.mdx
- apps/raddix/data/docs/utilities/use-counter/use-counter.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
Add documentation of useCounter hook
> docs: new useCounter hook

- apps/raddix/data/home/en.json
- apps/raddix/data/home/es.json
- apps/raddix/src/components/features.tsx
- apps/raddix/src/components/hero.tsx
- apps/raddix/src/layouts/home.tsx
- apps/raddix/src/pages/index.tsx
- apps/raddix/src/types/home-data.ts
The design of the `hero` component was renewed, and a new component was added that contains the features of Raddix
> feat: update home page

- apps/raddix/data/docs/hooks/use-interval/use-interval.en.mdx
- apps/raddix/data/docs/hooks/use-interval/use-interval.es.mdx
- apps/raddix/data/docs/hooks/use-timeout/use-timeout.en.mdx
- apps/raddix/data/docs/hooks/use-timeout/use-timeout.es.mdx
- apps/raddix/examples/use-interval/example1.tsx
- apps/raddix/examples/use-interval/example2.tsx
- apps/raddix/examples/use-timeout/example1.tsx
- package.json
- pnpm-lock.yaml
Add documentation for useInterval and useTimeout hooks
> docs(raddix): add documentation for useInterval and useTimeout hooks

- apps/raddix/data/docs/hooks/use-media-query/use-media-query.en.mdx
- apps/raddix/data/docs/hooks/use-media-query/use-media-query.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
- apps/raddix/examples/use-media-query/example1.tsx
- apps/raddix/examples/use-media-query/example2.tsx
- package.json
- pnpm-lock.yaml
Add documentation for useMediaQuery hook
> docs(raddix): add documentation for useMediaQuery hook

- apps/raddix/data/docs/hooks/use-event-listener/use-event-listener.en.mdx
- apps/raddix/data/docs/hooks/use-event-listener/use-event-listener.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
Add documentation for useEventListener hook
> docs(raddix): add documentation for useEventListener hook

- apps/raddix/data/docs/hooks/use-scroll-position/use-scroll-position.en.mdx
- apps/raddix/data/docs/hooks/use-scroll-position/use-scroll-position.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
Add documentation for useScrollPosition hook
> docs(raddix): add documentation for useScrollPosition hook

- apps/raddix/data/docs/hooks/use-window-size/use-window-size.en.mdx
- apps/raddix/data/docs/hooks/use-window-size/use-window-size.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
Add documentation for useWindowSize hook
> docs(raddix): add documentation for useWindowSize hook

- apps/raddix/data/docs/hooks/use-counter/use-counter.en.mdx
- apps/raddix/data/docs/hooks/use-counter/use-counter.es.mdx
- apps/raddix/data/sidebar/en.json
- apps/raddix/data/sidebar/es.json
Add examples and features of useCounter hook
> feat(raddix): improvement `useCounter` documentation

- apps/raddix/data/header/en.json
- apps/raddix/data/header/es.json
- apps/raddix/src/app/[lang]/layout.tsx
- apps/raddix/src/app/[lang]/providers.tsx
- apps/raddix/src/components/api-table.tsx
- apps/raddix/src/components/button.tsx
- apps/raddix/src/components/code-block/code-block.tsx
- apps/raddix/src/components/code-block/theme.ts
- apps/raddix/src/components/code.tsx
- apps/raddix/src/components/copy.tsx
- apps/raddix/src/components/features.tsx
- apps/raddix/src/components/header.tsx
- apps/raddix/src/components/hero.tsx
- apps/raddix/src/components/language-switcher.tsx
- apps/raddix/src/components/mdx.tsx
- apps/raddix/src/components/snippet.tsx
- apps/raddix/src/components/theme-switcher.tsx
- apps/raddix/src/contexts/theme-context.tsx
- apps/raddix/src/hooks/useDarkMode.ts
- apps/raddix/src/icons/moon.tsx
- apps/raddix/src/icons/sun.tsx
- apps/raddix/src/lib/cookie.ts
- apps/raddix/src/styles/main.css
- apps/raddix/src/utils/get-theme.ts
- packages/vintex/src/footer/footer.tsx
- packages/vintex/src/pagenav/pagenav.tsx
- packages/vintex/src/pagination/pagination.tsx
- packages/vintex/src/sidebar/sidebar.tsx
- settings/tailwind/tailwind.config.ts
This PR brings the following changes:
- Dark mode configuration in tailwind.
- Added support for light mode on the Raddix page (dark mode is loaded by default)
> feat: light mode

- apps/raddix/package.json
- apps/raddix/src/app/[lang]/layout.tsx
- pnpm-lock.yaml
Add [Vercel Web Analytics](https://vercel.com/docs/speed-insights/quickstart#add-the-speedinsights-component-to-your-app) and [Vercel Speed Insights](https://vercel.com/docs/speed-insights/quickstart#add-the-speedinsights-component-to-your-app)
> chore(raddix): add web analytics and speed insights

- apps/raddix/content/guide/get-guide.ts
- apps/raddix/data/header/en.json
- apps/raddix/data/header/es.json
- apps/raddix/src/components/header.tsx
- apps/raddix/src/components/search/index.tsx
- apps/raddix/src/components/search/search-box.tsx
- apps/raddix/src/components/search/search-results.tsx
- apps/raddix/src/components/search/types.ts
- apps/raddix/src/hooks/useAutocomplete.ts
- apps/raddix/src/hooks/useCurrentSlug.ts
- apps/raddix/src/hooks/useIsMobile.ts
- apps/raddix/src/i18n/useLocale.ts
- apps/raddix/src/icons/code.tsx
- apps/raddix/src/icons/file.tsx
- apps/raddix/src/icons/search.tsx
- apps/raddix/src/pages/api/hook.ts
- apps/raddix/src/styles/main.css
- packages/vintex/src/sidebar/sidebar.tsx
A search modal powered by algolia
> feat(raddix): add search modal
